name: maven compile test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Validate and Compile with Maven
      run: mvn validate compile
    - name: Lint Check Maven
      run: mvn release:prepare
